Repository rupali-p/recycling-app, pull requests merged in 2023-10, with the labels that each got.

#25 Clodagh/login
  administration/Clodagh/Sprint2/PIC Research.pdf
  client/src/views/Login.js
  flask-server/login.py
  flask-server/server.py
Labels: enhancement

#36 Fixing Login Defect
  .gitignore
  client/src/views/Login.js
  flask-server/__pycache__/register_user.cpython-311.pyc
Labels: bug

#34 Resuable Result Pages
  client/public/index.html
  client/src/App.js
  client/src/css/Common.css
  client/src/images/red_bin.png
  client/src/images/yellow_bin.png
  client/src/views/RedBinResult.js
  client/src/views/YellowBinResult.js
Labels: blocked

#40 Fixed White Borders on pages and changed title from 'React App' to 'Hamlet'
  client/src/css/Common.css
  client/src/views/Account.js
  client/src/views/Checklist.js
  client/src/views/Home.js
  client/src/views/UploadImage.js
Labels: blocked

#51 Main bug fix
  client/src/views/Account.js
  flask-server/account_details.py
  flask-server/server.py
Labels: bug, enhancement
